### ISSUE TITLE
AAI Miners

### ISSUE THREAD

**Issue by hasezoey** [VortiK/vtk-deep-core-mining#1]
i noticed that the AAI Miners can mine the deep core patches
and the "Zoner" indentifys the patches as an ore
Is it wanted like that?

Factorio 0.16.51
Mod Version: 1.11.4
(Windows 10)

**Comment by VortiK** [comment]
Hello, 

Thanks for the report, that's not explicitly expected. I guess AAI Miners are coded to mine any ore. I'll check if AAI has a way to specify a restriction. Indeed deep core ore is designed to be mined specifically with its mining machines, especially in the case of required sulfuric acid.

Regards

**Comment by VortiK** [comment]
After checking AAI code there doesn't seems to be an easy way to prevent this sorry.

I guess you can "manually" add a condition to ignore specific tiles in your AAI scanner circuit as a workaround.

**Comment by VortiK** [comment]
Gotcha, so the problem is that you have AAI miners going to mining zones put on top of deep core ores where I guess you have deep core miner on ? Maybe you could instead put a "no go zone" with the zone planner tool and again add a circuit to ignore them ?

Means you'll have to put ignore zone on all deep core ore tho so it might not be an optimal workaround.

I'll dig a bit more if I can find another solution.

**Comment by hasezoey** [comment]
Problem was i had not researched the deep ore miner and all that stuff, and now i have AAI not installed anymore 
(performance reasons, really bad AI (miners, haulers all get stuck in some wall or transportbelt) and that the deep ore patches only spawn when some ore is / got mined, and my setup always check if there is this ore, when yes do nothing (place the same zone as before) and otherwise delete the zone ...)

**Comment by VortiK** [comment]
![image](https://user-images.githubusercontent.com/23299769/45386980-ff157e80-b614-11e8-84f6-2f7f79faf2da.png)

Just in case it could be usefull I've made a test to not place zones if a specific building is also present, it works. Just add a combinator in the scanner output before any other processing.

**Comment by hasezoey** [comment]
i know, but like i said, i didnt had it researched (i couldnt build these buildings)

**Comment by VortiK** [comment]
Yeah, it just a workaround :)

The AAI Miner do actually mine the deep ore patches so it still working until you have the deep core miner.
Although the patch is infinite so it can be considered unbalanced in a way but properly preventing it would be much work for the minor issue it is.
