### ISSUE TITLE
Moho Drill producing deep core chunks

### ISSUE THREAD

**Issue by ruiluth** [VortiK/vtk-deep-core-mining#15]
I can't figure out why, but my moho drills are producing deep core chunks in addition to raw ore. They are useless without further research, and as a result my ore lines are clogged with core chunks. As far as I can tell, this is not intended behavior, and I seem to recall moho drills only producing usable ore in previous versions, so I'm reporting it as an issue.

Tested using Factorio 1.1.150 and Deep Core Mining 2.7.1. No other mods affecting ores or the drill itself.

**Comment by VortiK** [comment]
Hello, 

I would still need the mod list and ideally a savegame to reproduce this issue. Most of the time this bug appear was because of a conflict preventing the event triggering the ore patch swapping from doing its job.

**Comment by ruiluth** [comment]
[mod-list.json.txt](https://github.com/VortiK/vtk-deep-core-mining/files/7804331/mod-list.json.txt)

After disabling and re-enabling all my mods, as well as picking up and replacing the drills, they're now working properly. A few are outdated though, so I'll remove those. Thank you for the response, if it comes up again I'll do some more digging and try to find more information.

**Comment by VortiK** [comment]
Glad to hear it ! :)
