### ISSUE TITLE
Can't be used with the new game plus mod

### ISSUE THREAD

**Issue by Bilka2** [VortiK/vtk-deep-core-mining#2]
Due to https://github.com/VortiK/vtk-deep-core-mining/blob/master/lib/resource.lua#L141 your mod cannot be used with my mod, new game plus: https://mods.factorio.com/mod/NewGamePlus/discussion/5c29e839dd11c4000d2f9847

This could be solved by spawning your resource on surfaces with "my" name (https://github.com/Bilka2/NewGamePlus/blob/master/control.lua#L485) additionally to nauivs.

**Comment by VortiK** [comment]
Hello @Bilka2 thanks for the report, this is fixed in 1.13.0 !

**Comment by Bilka2** [comment]
Thank you!
