### ISSUE TITLE
support for custom ores where name value is not equal to result name value is not working

### ISSUE THREAD

**Issue by Atlntssplayer** [VortiK/vtk-deep-core-mining#22]
Hello

A buddy of mine who likes your mod deep core mining asked me to double check something he found

Some custom ores made by other mods are not working with your mod, meaning that deep core ore patches won't spawn when those custom ore patches are depleted
I didn't check deep core cracks only ore patches

I tested quite a few mods and found this:

When a mod defines it's custom ore there is a name and a mining / result

For example in the case of Krastorio2:

data:extend({
  {
    type = "resource",
    name = "imersite",
.
.
.
minable = {
      hardness = 1,
      mining_time = 2,
      result = "raw-imersite",
.
.
.

Only pattern I was able to find when trying to figure out which mod's custom ores are supported and which ones not is that where these two names are differenl (name  ="" and minable --> result ="") ore patches won't be spawned by your mod

I'm not a dev and I know very little about code so I'cant tell why but this seemed to be a pattern which might help figure this out

Examples to back this up:

Ores from these mods are supported by your mod and they all spawn permanent deep core patches
Looking at their ore definitions the name and minable values are equal in all cases

bob's ore
leighzermorphite
bztungsten
bzlead
bzzirconium
clowns-extended-minerals

In the case of the following mods your mod won't spawn ore patches after their ore depletion even for the two which have built in support in your mod

SimpleSilicon
Brimstuff
Krastorio2

In all these mods the name and minable / result values are different:
name = "SiSi-quartz-ore" but result = "SiSi-quartz"
name = "sulfur-ore" but result = "sulfur"
name = "imersite" but result = "raw-imersite"

In the case of two of these mods I know your mod has built in compatiblity and you accounted for the name and mining/result value differences but still for some reason it wasn't enough

Another smaller issue I was able to confirm is that the settings which would govern if patches would spawn after a supported mod's ore and also the vanilla ores are not working
These settings worked in version 2.8.2 but are not part of active code since 2.9.0 where you implemented the automatic ore support

I hope you will be able to figure out what actually makes a few custom ores not spawn ore patches because after quite some hours i wasn't able to come up with anything other than what I wrote down here

Thank you for this great mod it's a good idea

**Comment by VortiK** [comment]
Hello, thanks for your detailed report, I will look into it as soon as I can !
