### ISSUE TITLE
0.17.5 update broke mod - mining-productivity-12 does not exist

### ISSUE THREAD

**Issue by TheEisbaer** [VortiK/vtk-deep-core-mining#4]
![image](https://user-images.githubusercontent.com/3662507/53756116-a387c780-3eb8-11e9-9f5d-6c2fff35e22c.png)

**Comment by VortiK** [comment]
Hello, 

This is caused by Factorio 0.17.5 that refactored the mining productivity technologies. I've just push a new version that fixed this.

Regards
