### ISSUE TITLE
newOreEntity missing local

### ISSUE THREAD

**Issue by BoskiDialer** [VortiK/vtk-deep-core-mining#7]
https://github.com/VortiK/vtk-deep-core-mining/blob/525bb17ede8118980ff7fea79b47710032012bbe/lib/resource.lua#L139

variable newOreEntity does not have `local` so entity ref will not be serialised during save and so desync is possible

**Comment by VortiK** [comment]
Thanks for this report, sorry I didn't see it earlier ! It is fixed in 1.21.1 now.
